# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Blog on Data Analytics
email: kazmialiarsalan@gmail.com
description: Ali Arsalan Kazmi
baseurl: "/CNN_Scale_problem" # the subpath of your site, e.g. /blog


url: "https://github.com/henrychacon/" # the base hostname & protocol for your site
twitter_username: scac1041
github_username:  henrychacon
disqus_shortname: henrychacon

# Build settings
markdown: kramdown
encoding: UTF-8

# Enable 'future' posts?
future: true 
theme: jekyll-theme-cayman
