title: beta.gouv.fr
email: contact@beta.gouv.fr
description: Nous créons des services publics numériques
baseurl: "" # the subpath of your site, e.g. /blog
url: https://github.com/henrychacon/CNN_Scale_problem # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BetaGouv
#github_username:  betagouv
#github_repository: BetaGouv/beta.gouv.fr

# Build settings
#markdown: kramdown



theme: jekyll-theme-cayman
